linked_list_to_file:	linked_list_to_file.o linkedList.o
	gcc linked_list_to_file.o linkedList.o -o lltf

linked_list_to_file.o:	linked_list_to_file.c linkedList.h projectStructure.h
	gcc -c linked_list_to_file.c

linkedList.o:	linkedList.c linkedList.h
	gcc -c linkedList.c

